services:
  nextjs:
    image: cab432-cloud-project-nextjs-dev
    container_name: cab432-cloud-project-nextjs-dev
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
    depends_on:
      - redis
    networks:
      - shared-network

      
  redis:
    image: redis:7.2
    container_name: cab432-cloud-project-redis-dev
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - shared-network

volumes:
  node_modules:
  redis-data:

networks:
  shared-network: