import "./globals.css";
import { Montserrat } from "next/font/google";
import { UIProvider, NextAuthProvider } from "./providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Image Converter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className="bg-blue-950 text-white">
        <UIProvider>
          <NextAuthProvider>
            <div className="flex h-screen flex-col">
              <Header />
              {children}
              <Footer />
            </div>
          </NextAuthProvider>
        </UIProvider>
      </body>
    </html>
  );
}
